language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
  allow_failures:
    - php: hhvm

cache:
  directories:
    - vendor/
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer self-update

install: 
  - cp phpunit.xml.dist phpunit.xml
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml tests/
