language: php

php:
  - 7.0
  - 7.1

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - vendor/
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer self-update

install: 
  - cp phpunit.xml.dist phpunit.xml
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml tests/
